import { Inter } from "next/font/google";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import SideNav from "./Components/SideNav";
import AuthProvider from "./Provider";

import RightNav from "./Components/RightNav";
import BottomNav from "./Components/BottomNav";
import NextTopLoader from "nextjs-toploader";

const inter = Open_Sans({ subsets: ["latin"] ,display:"block"});

export const dynamic = 'force-dynamic'
export const revalidate = 0

export const metadata = {
  title: "Lumon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <AuthProvider>
      
      <body className={ `text-black  ${inter.className}` }>
      
      <NextTopLoader color="black" height={5}/>
        <div className="mx-auto flex justify-center ">
        <SideNav/>
         <div className="w-[33rem] min-h-[90vh]  mb-20 border-x-[1px] border-[rgb(219, 219, 219)] ">
         {children}
         </div>
         <RightNav/>
        <BottomNav/>
         
        </div>
        
        
        </body>
      </AuthProvider>
    </html>
  );
}
